# Generated by Django 3.2.6 on 2023-07-02 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0023_auto_20230702_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='Product_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.product_name'),
        ),
        migrations.AddField(
            model_name='items',
            name='Technician',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='items.technician'),
        ),
    ]
