# Generated by Django 3.2.6 on 2023-07-02 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0024_auto_20230702_0707'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='items',
            name='Supplied_by',
        ),
        migrations.AddField(
            model_name='items',
            name='Issue_date',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='items',
            name='Vendor',
            field=models.TextField(blank=True, null=True, verbose_name='Supplied by'),
        ),
    ]
